package com.google.service.ws_cxf_intercepter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-23T00:22:19.425+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://ws_cxf_intercepter.service.google.com/", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws_cxf_intercepter.service.google.com/", className = "com.google.service.ws_cxf_intercepter.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws_cxf_intercepter.service.google.com/", className = "com.google.service.ws_cxf_intercepter.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
